// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obshcbemsezvokyevlzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ic2hjYmVtc2V6dm9reWV2bHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDg5OTcsImV4cCI6MjA2NzI4NDk5N30._PZr_5bmWwD60mW5eRhRoTDUk7o5_oDuvp9d5EtaQ8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});